# Site settings
title: Diego De Souza
email: diegotrus7@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  When I thought I couldn't go on, I forced myself to keep going.
   My success is based on persistence and effort, not luck.

   "Everything is possible for one who believes."

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://diegodesouza.github.io" # the base hostname & protocol for your site
twitter_username: diegotrus7
github_username:  diegodesouza

# Build settings
markdown: kramdown
